package zhttp

import (
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

func Header(fp io.Writer, pkg string) error {
	_, err := fp.Write([]byte("// Code generated by pack.go; DO NOT EDIT.\n\n"))
	if err != nil {
		return err
	}
	_, err = fp.Write([]byte("package " + pkg + "\n\n"))
	return err
}

func PackDir(fp io.Writer, varname, dir string) (closeErr error) {
	_, err := fp.Write([]byte("var " + varname + " = map[string][]byte{\n"))
	if err != nil {
		return err
	}

	err = filepath.Walk(dir, func(path string, st os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if st.IsDir() {
			return nil
		}

		d, err := ioutil.ReadFile(path)
		if err != nil {
			return err
		}

		_, err = fmt.Fprintf(fp, "\t\"%s\": %s,\n\n", path, asbyte(d))
		return err
	})
	if err != nil {
		return err
	}

	_, err = fp.Write([]byte("}\n\n"))
	if err != nil {
		return err
	}

	return closeErr
}

func asbyte(s []byte) string {
	var b strings.Builder
	for _, c := range s {
		b.WriteString(fmt.Sprintf("%#x, ", c))
	}
	return "[]byte{" + b.String() + "}"
}
